=== osframework/contract-date/contract-date-fincal/src/main/resources/org/osframework/contract/date/fincal/config/xml/definitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://osframework.org/schema/contract-date/definitions"
	xmlns="http://osframework.org/schema/contract-date/definitions"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">

	<xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>

	<xsd:annotation>
		<xsd:documentation xml:lang="en"><![CDATA[
		Financial Calendar Definitions Schema, version 1.0
		Author: Dave Joyce
		Defines a simple structure for fully specifying world holidays and
		the combinations of holidays that comprise bank holiday calendars
		for world financial markets.
		]]></xsd:documentation>
	</xsd:annotation>

	<xsd:complexType name="IdentifiedType" abstract="true">
		<xsd:annotation>
			<xsd:documentation xml:lang="en"><![CDATA[
			Abstract supertype of data types for uniquely identified
			definition entities.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="id" type="xsd:token" use="required" />
	</xsd:complexType>

	<xsd:simpleType name="CurrencyType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en"><![CDATA[
			Data type for a valid ISO-4217 currency.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:token">
			<xsd:pattern value="[A-Z]{3}" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="CentralBankType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en"><![CDATA[
			Represents a distinct world central bank. A central bank issues a
			particular currency.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="IdentifiedType">
				<xsd:sequence>
					<xsd:element name="name" type="xsd:token" minOccurs="1" maxOccurs="1" />
					<xsd:element name="currency" type="CurrencyType" minOccurs="1" maxOccurs="1" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="CentralBanksType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en"><![CDATA[
			A list of uniquely identified central banks.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="centralBank" type="CentralBankType" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="HolidayType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en"><![CDATA[
			Represents a distinct holiday observed on 1 or more financial
			calendars worldwide. Specifically, elements of this type describe
			the method by which the holiday is produced for a given Gregorian
			calendar year.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="IdentifiedType">
				<xsd:sequence>
					<xsd:element name="name" type="xsd:token" minOccurs="1" maxOccurs="1" />
					<xsd:element name="description" type="xsd:string" minOccurs="0" />
					<xsd:element name="observance" minOccurs="1" maxOccurs="1">
						<xsd:simpleType>
							<xsd:restriction base="xsd:token">
								<xsd:enumeration value="CALCULATED" />
								<xsd:enumeration value="FIXED" />
								<xsd:enumeration value="ONETIME" />
								<xsd:enumeration value="RELATIVE" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="expression" type="xsd:token" minOccurs="1" maxOccurs="1" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="HolidaysType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en"><![CDATA[
			A list of uniquely identified world holidays.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="holiday" type="HolidayType" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CalendarType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en"><![CDATA[
			Represents a bank holiday calendar for a single financial market.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="IdentifiedType">
				<xsd:sequence>
					<xsd:element name="description" type="xsd:string" minOccurs="0" />
					<xsd:element name="centralBank" minOccurs="0">
						<xsd:complexType>
							<xsd:attribute name="refid" type="xsd:token" use="required" />
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="holidays">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="holiday" minOccurs="1" maxOccurs="unbounded">
									<xsd:complexType>
										<xsd:attribute name="refid" type="xsd:token" use="required" />
									</xsd:complexType>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="CalendarsType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en"><![CDATA[
			A list of uniquely identified financial holiday calendars.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="calendar" type="CalendarType" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="DefinitionsType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en"><![CDATA[Describe here]]></xsd:documentation>
		</xsd:annotation>
		<xsd:all>
			<xsd:element name="centralBanks" type="CentralBanksType" minOccurs="1" maxOccurs="1" />
			<xsd:element name="holidays" type="HolidaysType" minOccurs="1" maxOccurs="1" />
			<xsd:element name="calendars" type="CalendarsType" minOccurs="1" maxOccurs="1" />
		</xsd:all>
	</xsd:complexType>

	<xsd:element name="definitions" type="DefinitionsType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en"><![CDATA[Describe here]]></xsd:documentation>
		</xsd:annotation>
		<xsd:key name="holidayIdKey">
			<xsd:selector xpath="holidays/holiday" />
			<xsd:field xpath="@id" />
		</xsd:key>
		<xsd:keyref name="holidayIdKeyRef" refer="holidayIdKey">
			<xsd:selector xpath="calendars/calendar/holidays/holiday" />
			<xsd:field xpath="@refid" />
		</xsd:keyref>
		<xsd:key name="centralBankIdKey">
			<xsd:selector xpath="centralBanks/centralBank" />
			<xsd:field xpath="@id" />
		</xsd:key>
		<xsd:keyref name="centralBankIdKeyRef" refer="centralBankIdKey">
			<xsd:selector xpath="calendars/calendar/centralBank" />
			<xsd:field xpath="@refid" />
		</xsd:keyref>
		<xsd:unique name="calendarIdKey">
			<xsd:selector xpath="calendars/calendar" />
			<xsd:field xpath="@id" />
		</xsd:unique>
	</xsd:element>

</xsd:schema>

=== osframework/contract-date/contract-date-fincal/src/test/resources/definitions-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://osframework.org/schema/contract-date/definitions"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://osframework.org/schema/contract-date/definitions org/osframework/contract/date/fincal/config/xml/definitions.xsd">
	<centralBanks>
		<centralBank id="USFR">
			<name>United States Federal Reserve</name>
			<country>US</country>
			<currency>USD</currency>
		</centralBank>
		<centralBank id="BoE">
			<name>Bank of England</name>
			<country>UK</country>
			<currency>GBP</currency>
		</centralBank>
		<centralBank id="SNB">
			<name>Swiss National Bank</name>
			<country>CH</country>
			<currency>CHF</currency>
		</centralBank>
		<centralBank id="ECB">
			<name>European Central Bank</name>
			<country>EU</country>
			<currency>EUR</currency>
		</centralBank>
	</centralBanks>
	<holidays>
		<holiday id="NewYearsDay">
			<name>New Year's Day</name>
			<observance>FIXED</observance>
			<expression>JANUARY/01</expression>
		</holiday>
		<holiday id="StBertholdsDay">
			<name>St. Berthold's Day</name>
			<observance>FIXED</observance>
			<expression>JANUARY/02</expression>
		</holiday>
		<holiday id="MLKDay">
			<name>Martin Luther King Day</name>
			<observance>RELATIVE</observance>
			<expression>JANUARY/MONDAY/3</expression>
		</holiday>
		<holiday id="PresidentsDay">
			<name>Presidents' Day</name>
			<observance>RELATIVE</observance>
			<expression>FEBRUARY/MONDAY/3</expression>
		</holiday>
		<holiday id="GoodFriday">
			<name>Good Friday</name>
			<observance>CALCULATED</observance>
			<expression>EASTER-2</expression>
		</holiday>
		<holiday id="EasterMonday">
			<name>Easter Monday</name>
			<observance>CALCULATED</observance>
			<expression>EASTER+1</expression>
		</holiday>
		<holiday id="LabourDay">
			<name>Labour Day</name>
			<observance>FIXED</observance>
			<expression>MAY/01</expression>
		</holiday>
		<holiday id="EarlyMayBankHoliday">
			<name>Early May Bank Holiday</name>
			<observance>RELATIVE</observance>
			<expression>MAY/MONDAY/1</expression>
		</holiday>
		<holiday id="RobertSchumanDeclaration">
			<name>Anniversay of Robert Schuman's Declaration</name>
			<observance>FIXED</observance>
			<expression>MAY/09</expression>
		</holiday>
		<holiday id="MemorialDay">
			<name>Memorial Day</name>
			<observance>RELATIVE</observance>
			<expression>MAY/MONDAY/L</expression>
		</holiday>
		<holiday id="SpringBankHoliday">
			<name>Spring Bank Holiday</name>
			<observance>RELATIVE</observance>
			<expression>MAY/MONDAY/L</expression>
		</holiday>
		<holiday id="QueensDiamondJubilee">
			<name>The Queen's Diamond Jubilee</name>
			<observance>ONETIME</observance>
			<expression>2012-06-05</expression>
		</holiday>
		<holiday id="AscensionDay">
			<name>Ascension Day</name>
			<observance>CALCULATED</observance>
			<expression>EASTER+39</expression>
		</holiday>
		<holiday id="WhitMonday">
			<name>Whit Monday</name>
			<observance>CALCULATED</observance>
			<expression>EASTER+50</expression>
		</holiday>
		<holiday id="CorpusChristi">
			<name>Corpus Christi</name>
			<observance>CALCULATED</observance>
			<expression>EASTER+60</expression>
		</holiday>
		<holiday id="IndependenceDay">
			<name>Independence Day</name>
			<observance>FIXED</observance>
			<expression>JULY/04</expression>
		</holiday>
		<holiday id="SwissNationalDay">
			<name>Swiss National Day</name>
			<observance>FIXED</observance>
			<expression>AUGUST/01</expression>
		</holiday>
		<holiday id="SummerBankHoliday">
			<name>Summer Bank Holiday</name>
			<description>Summer Bank Holiday (England, Northern Ireland, Wales)</description>
			<observance>RELATIVE</observance>
			<expression>AUGUST/MONDAY/L</expression>
		</holiday>
		<holiday id="LaborDay">
			<name>Labor Day</name>
			<observance>RELATIVE</observance>
			<expression>SEPTEMBER/MONDAY/1</expression>
		</holiday>
		<holiday id="DayOfGermanUnity">
			<name>Day of German Unity</name>
			<observance>FIXED</observance>
			<expression>OCTOBER/03</expression>
		</holiday>
		<holiday id="ColumbusDay">
			<name>Columbus Day</name>
			<observance>RELATIVE</observance>
			<expression>OCTOBER/MONDAY/2</expression>
		</holiday>
		<holiday id="AllSaintsDay">
			<name>All Saints' Day</name>
			<observance>FIXED</observance>
			<expression>NOVEMBER/01</expression>
		</holiday>
		<holiday id="VeteransDay">
			<name>Veterans Day</name>
			<observance>FIXED</observance>
			<expression>NOVEMBER/11</expression>
		</holiday>
		<holiday id="ThanksgivingUS">
			<name>Thanksgiving</name>
			<description>Thanksgiving (US)</description>
			<observance>RELATIVE</observance>
			<expression>NOVEMBER/THURSDAY/4</expression>
		</holiday>
		<holiday id="ChristmasEve">
			<name>Christmas Eve</name>
			<observance>FIXED</observance>
			<expression>DECEMBER/24</expression>
		</holiday>
		<holiday id="Christmas">
			<name>Christmas Day</name>
			<observance>FIXED</observance>
			<expression>DECEMBER/25</expression>
		</holiday>
		<holiday id="BoxingDay">
			<name>Boxing Day</name>
			<observance>FIXED</observance>
			<expression>DECEMBER/26</expression>
		</holiday>
		<holiday id="ChristmasHoliday">
			<name>Christmas Holiday</name>
			<observance>FIXED</observance>
			<expression>DECEMBER/26</expression>
		</holiday>
		<holiday id="StStephansDay">
			<name>St. Stephan's Day</name>
			<observance>FIXED</observance>
			<expression>DECEMBER/26</expression>
		</holiday>
		<holiday id="NewYearsEve">
			<name>New Year's Eve</name>
			<observance>FIXED</observance>
			<expression>DECEMBER/31</expression>
		</holiday>
	</holidays>
	<calendars>
		<calendar id="LnB">
			<description>London bank holidays</description>
			<centralBank refid="BoE" />
			<holidays>
				<holiday refid="NewYearsDay" />
				<holiday refid="GoodFriday" />
				<holiday refid="EasterMonday" />
				<holiday refid="EarlyMayBankHoliday" />
				<holiday refid="SpringBankHoliday" />
				<holiday refid="QueensDiamondJubilee" />
				<holiday refid="SummerBankHoliday" />
				<holiday refid="Christmas" />
				<holiday refid="BoxingDay" />
			</holidays>
		</calendar>
		<calendar id="NCH">
			<description>Swiss Interbank Clearing System holidays</description>
			<centralBank refid="SNB" />
			<holidays>
				<holiday refid="NewYearsDay" />
				<holiday refid="StBertholdsDay" />
				<holiday refid="GoodFriday" />
				<holiday refid="EasterMonday" />
				<holiday refid="LabourDay" />
				<holiday refid="AscensionDay" />
				<holiday refid="WhitMonday" />
				<holiday refid="SwissNationalDay" />
				<holiday refid="Christmas" />
				<holiday refid="StStephansDay" />
			</holidays>
		</calendar>
		<calendar id="NYB">
			<description>New York bank holidays</description>
			<centralBank refid="USFR" />
			<holidays>
				<holiday refid="NewYearsDay" />
				<holiday refid="MLKDay" />
				<holiday refid="PresidentsDay" />
				<holiday refid="MemorialDay" />
				<holiday refid="IndependenceDay" />
				<holiday refid="LaborDay" />
				<holiday refid="ColumbusDay" />
				<holiday refid="VeteransDay" />
				<holiday refid="ThanksgivingUS" />
				<holiday refid="Christmas" />
			</holidays>
		</calendar>
		<calendar id="Tgt">
			<description>TARGET holidays (European Union)</description>
			<centralBank refid="ECB" />
			<holidays>
				<holiday refid="NewYearsDay" />
				<holiday refid="GoodFriday" />
				<holiday refid="EasterMonday" />
				<holiday refid="LabourDay" />
				<holiday refid="RobertSchumanDeclaration" />
				<holiday refid="AscensionDay" />
				<holiday refid="WhitMonday" />
				<holiday refid="CorpusChristi" />
				<holiday refid="DayOfGermanUnity" />
				<holiday refid="AllSaintsDay" />
				<holiday refid="ChristmasEve" />
				<holiday refid="Christmas" />
				<holiday refid="ChristmasHoliday" />
				<holiday refid="NewYearsEve" />
			</holidays>
		</calendar>
	</calendars>
</definitions>
